### 회원가입

POST http://localhost:8090/auth/signup
Content-Type: application/json

{
  "name": "sol",
  "email": "sol@gmail.com",
  "password": "1234"
}


### 로그인

POST http://localhost:8090/auth/login
Content-Type: application/json

{
  "email": "sol@gmail.com",
  "password": "1234"
}


### 사용자 페이지
GET http://localhost:8090/user

### 관리자 페이지
GET http://localhost:8090/admin

### 메인 페이지
GET http://localhost:8090